# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: java with CI/CD

on:
  release:
    types: [created]
  workflow_dispatch:  # Add manual trigger
    inputs:           # Optional inputs for manual trigger
      manual_trigger:
        description: 'Manually trigger the workflow'
        default: 'true' 

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file


    - name: Build and Test Spring Boot
      run: |
          cd TravelHub-Backend/
          chmod +x mvnw
          ./mvnw clean install

    - name: Build and Test Angular
      run: |
          cd TravelHub-frontend/
          npm install
          ng build --prod
